linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - golint
    - gosec
    - lll
    - maligned
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - scopelint
        - bodyclose
        - lll
        - noctx
    - path: main.go
      linters:
        - errcheck
